version: '3.7'

services:
  auth_api:
    build: .
    depends_on:
      - redis
#      - auth_db

#  nginx:
#    image: nginx:1.23.1
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf:ro
#      - ./src/core:/etc/nginx/conf.d:ro
#    depends_on:
#      - auth_api
#    ports:
#      - "80:80"
#      - "5000:80"

  redis:
    image: redis:6.2-alpine
    expose:
      - "6379"
    command: redis-server --requirepass ${redis_password}
    volumes:
      - redis:/data
    env_file:
      - .env

  auth_db:
    tty: true
    image: postgres:14.5-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data/
    expose:
      - "5433"
    environment:
      POSTGRES_DB: movies_database
      POSTGRES_USER: app
      POSTGRES_PASSWORD: 123qwe

volumes:
  redis:
  pg_data:
