version: '3.7'

services:
  auth_api:
    build: .
    command: /bin/bash -c "flask run --host=0.0.0.0 --port=5000"
    expose:
      - "5000"
    depends_on:
      - auth_db
      - redis
    env_file:
      - .env

  nginx:
    image: nginx:1.23.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./src/core:/etc/nginx/conf.d:ro
    depends_on:
      - auth_api
    ports:
      - "80:80"
      - "5000:80"

  redis:
    image: redis:6.2-alpine
    expose:
      - "6379"
    command: redis-server --requirepass ${redis_password}
    volumes:
      - redis:/data
    env_file:
      - .env

  redis_rl:
    image: redis:6.2-alpine
    expose:
      - "4242"
    command: redis-server --requirepass ${redis_password}
    volumes:
      - redis:/data
    env_file:
      - .env

  auth_db:
    tty: true
    image: postgres:14.5-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data/
      - ./docker/init-script.sql:/docker-entrypoint-initdb.d/init-script.sql
    expose:
      - "5432"
    env_file: .env

  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - "6831:6831/udp"
      - "16686:16686"
    depends_on:
      - auth_db

volumes:
  redis:
  postgres-data:
