"""empty message

Revision ID: 19768c507b65
Revises: 
Create Date: 2022-11-07 18:55:00.929668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19768c507b65'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('login', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('test_field', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.create_table('session_history',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('action', sa.Text(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('user_device_type', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id', 'user_device_type'),
    sa.UniqueConstraint('id', 'user_device_type'),
    postgresql_partition_by='LIST (user_device_type)'
    )
    op.create_table('users_n_roles',
    sa.Column('users_id', sa.Text(), nullable=False),
    sa.Column('roles_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['roles_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('users_id', 'roles_id')
    )

    from src.models.session_history import create_table_login_history_partition_ddl
    from src.models.models import PARTITION_TABLES_REGISTRY
    for table_class, device_type in PARTITION_TABLES_REGISTRY:
        ddl = create_table_login_history_partition_ddl(
            table_class.__table__,
            device_type
        )
        ddl(target=None, bind=op.get_bind())

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_n_roles')
    op.drop_table('session_history')
    op.drop_table('users')
    op.drop_table('roles')
    # ### end Alembic commands ###
