"""Added VK registratoin

Revision ID: 633f3b3a1889
Revises: 19768c507b65
Create Date: 2022-11-16 17:42:55.615204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '633f3b3a1889'
down_revision = '19768c507b65'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registration_servises',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name_service', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name_service'),
    sa.UniqueConstraint('url')
    )
    op.create_unique_constraint(None, 'roles', ['id'])
    op.create_unique_constraint(None, 'session_history', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # op.drop_column('users', 'test_field')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('test_field', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'session_history', type_='unique')
    op.drop_constraint(None, 'roles', type_='unique')
    op.drop_table('registration_servises')
    # ### end Alembic commands ###
